import { useCallback, useEffect, useState } from 'react';
import { ArrowBigUp, CheckCircle2, Lightbulb } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';

type Feature = { id: string; title: string; description: string; status: 'open'|'reviewing'|'planned'|'deployed'|'declined'; decision_note: string | null; created_at: string; deployed_at: string | null; vote_count: number; voted_by_me: boolean | null };
const labels: Record<Feature['status'], string> = { open: 'Open', reviewing: 'Reviewing', planned: 'Planned', deployed: 'Deployed', declined: 'Not planned' };
const colors: Record<Feature['status'], string> = { open: 'bg-slate-100 text-slate-700', reviewing: 'bg-amber-100 text-amber-800', planned: 'bg-blue-100 text-blue-800', deployed: 'bg-emerald-100 text-emerald-800', declined: 'bg-gray-100 text-gray-600' };

export default function FeatureBoard() {
  const { user } = useAuth(); const { showToast } = useToast();
  const [items,setItems] = useState<Feature[]>([]); const [admin,setAdmin] = useState(false); const [loading,setLoading] = useState(true); const [title,setTitle] = useState(''); const [description,setDescription] = useState(''); const [busy,setBusy] = useState(false); const [filter,setFilter] = useState<'all'|Feature['status']>('all');
  const load = useCallback(async () => {
    setLoading(true);
    const [board, role] = await Promise.all([
      supabase.from('wrxs_feature_board' as never).select('*').order('vote_count',{ascending:false}).order('created_at',{ascending:false}),
      supabase.from('wrxs_platform_admins' as never).select('user_id').eq('user_id',user?.id || '').maybeSingle(),
    ]);
    if (board.error) showToast('Unable to load the feature board.', 'error'); else setItems((board.data || []) as Feature[]);
    setAdmin(Boolean(role.data)); setLoading(false);
  },[showToast,user?.id]);
  useEffect(() => { void load(); },[load]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!user || busy || !title.trim() || !description.trim()) return; setBusy(true); const { error } = await supabase.from('wrxs_feature_requests' as never).insert({ title:title.trim(), description:description.trim(), created_by:user.id } as never); if(error) showToast(error.message,'error'); else { setTitle(''); setDescription(''); showToast('Feature request submitted.','success'); await load(); } setBusy(false); }
  async function vote(item: Feature) { if (!user || busy) return; setBusy(true); const request = supabase.from('wrxs_feature_votes' as never); const { error } = item.voted_by_me ? await request.delete().eq('feature_request_id',item.id).eq('user_id',user.id) : await request.insert({feature_request_id:item.id,user_id:user.id} as never); if(error) showToast(error.message,'error'); else await load(); setBusy(false); }
  async function changeStatus(item: Feature, status: Feature['status']) { if (!admin || busy) return; setBusy(true); const patch = { status, deployed_at: status==='deployed' ? new Date().toISOString() : null, deployed_by: status==='deployed' ? user?.id : null }; const { error } = await supabase.from('wrxs_feature_requests' as never).update(patch as never).eq('id',item.id); if(error) showToast(error.message,'error'); else { showToast('Feature status updated.','success'); await load(); } setBusy(false); }
  const visible = filter==='all' ? items : items.filter(item=>item.status===filter);
  return <div className="mx-auto max-w-4xl"><div className="mb-6"><div className="flex items-center gap-3"><Lightbulb className="text-amber-500"/><h1 className="text-2xl font-semibold text-gray-950">Feature requests</h1></div><p className="mt-2 text-gray-600">Suggest what would make wrxs more useful, then vote for the ideas you want next.</p></div>
    <form onSubmit={submit} className="rounded-2xl border border-gray-200 bg-white p-5"><label className="text-sm font-medium">Feature title</label><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} required placeholder="What should wrxs help with?" className="mt-2 w-full rounded-xl border border-gray-300 px-3 py-2"/><label className="mt-4 block text-sm font-medium">Why would it help?</label><textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={3000} required rows={3} placeholder="Describe the outcome and how you would use it." className="mt-2 w-full rounded-xl border border-gray-300 px-3 py-2"/><button disabled={busy} className="mt-3 rounded-xl bg-slate-950 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">Submit request</button></form>
    <div className="mt-7 flex flex-wrap gap-2">{(['all','open','reviewing','planned','deployed'] as const).map(value=><button key={value} onClick={()=>setFilter(value)} className={`rounded-full px-3 py-1.5 text-sm ${filter===value?'bg-slate-950 text-white':'bg-white text-gray-600 ring-1 ring-gray-200'}`}>{value==='all'?'All':labels[value]}</button>)}</div>
    <div className="mt-4 space-y-3">{loading ? <p className="text-gray-500">Loading requests…</p> : visible.length===0 ? <p className="rounded-xl border border-dashed p-5 text-gray-500">No requests in this view yet.</p> : visible.map(item=><article key={item.id} className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex gap-4"><button disabled={busy} onClick={()=>vote(item)} className={`flex h-14 w-14 shrink-0 flex-col items-center justify-center rounded-xl ${item.voted_by_me?'bg-slate-950 text-white':'bg-gray-100 text-gray-700'}`} aria-label={`Vote for ${item.title}`}><ArrowBigUp size={20}/><span className="text-xs font-semibold">{item.vote_count}</span></button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-gray-950">{item.title}</h2><span className={`rounded-full px-2 py-0.5 text-xs font-medium ${colors[item.status]}`}>{item.status==='deployed' && <CheckCircle2 className="mr-1 inline" size={12}/>} {labels[item.status]}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-gray-600">{item.description}</p>{item.decision_note && <p className="mt-3 rounded-lg bg-gray-50 p-3 text-sm text-gray-700">{item.decision_note}</p>}<p className="mt-3 text-xs text-gray-400">Submitted {new Date(item.created_at).toLocaleDateString()}</p>{admin && <select value={item.status} onChange={e=>void changeStatus(item,e.target.value as Feature['status'])} disabled={busy} className="mt-3 rounded-lg border border-gray-300 bg-white px-2 py-1 text-sm"><option value="open">Open</option><option value="reviewing">Reviewing</option><option value="planned">Planned</option><option value="deployed">Deployed</option><option value="declined">Not planned</option></select>}</div></div></article>)}</div>
  </div>;
}
